---
title: 'Real Data Analysis: Ordinal LASSO'
output: html_document
date: "2023-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C:/Users/brian/Documents/Grad School/BIOS 735/HOOVS/")
library(data.table)
library(devtools)
library(caret)
library(dplyr)
library(tictoc)
library(psych)
load_all()

```

# Read in Data and create ordered factor

```{r }

data <- fread('C:/Users/brian/Documents/Grad School/BIOS 735/HOOVS/processed_data.csv')

y_factor_key <- data.frame(original = sort(unique(data$`B1:SATISFACTION W/LIFE`)),
                           y = factor(1:length(unique(data$`B1:SATISFACTION W/LIFE`)), ordered = T))

data_ordered_y <- merge(y_factor_key, data, by.x = "original", by.y = "B1:SATISFACTION W/LIFE") %>% 
  arrange(`W1 Case Id`) %>%
  select(-c("original", "W1 Case Id"))

data_ordered_y_scaled <- data_ordered_y
data_ordered_y_scaled[,2:199] <- as.data.frame(scale(data_ordered_y[,2:199]))

```

# Create train and test / folds within CV

```{r }

set.seed(5)

#Create training and testing set
train_test_i <- createDataPartition(y = data_ordered_y_scaled$y, p = 0.6, list = F)

data_train <- data_ordered_y_scaled[train_test_i,]
data_test <- data_ordered_y_scaled[-train_test_i,]

#Within training set, create folds
k <- 5 #set number of folds 
fold_indicies <- createFolds(y = data_train$y, k=k)

```

# K fold cross validation

```{r } 

lambda_grid <- seq(0, 0.05, 0.005)
J <- 5

all_model_info <- list()
best_lambda <- rep(NA, k)
best_kappa <- rep(NA, k)

for (fold in 1:k){
  
  #Fold Training and testing set
  fold_train <- data_train[-fold_indicies[[fold]],]
  fold_test <- data_train[fold_indicies[[fold]],]
  
  #Fit Ordinal LASSO
  tic(paste0("Fold #", fold))
  res.ordreg <- ordreg.lasso(
    formula = y ~ .,
    data = fold_train,
    lambdas = lambda_grid
  )
  toc()
  
  #Vector of Testing Kappas
  test_kappas <- rep(NA, length(res.ordreg$lambdas))
  
  #For each value of lambda of the fold, get kappa 
  for (i in 1:length(res.ordreg$lambdas)){
    
    #Predict
    predicted <- ordreg.predict(alpha = res.ordreg$alpha[i,], 
                                beta = res.ordreg$beta[i,], 
                                x = as.matrix(fold_test[,-1]))
    
    #Calculate Kappa
    test_kappas[i] <- cohen.kappa(x = matrix(c(fold_test[,1], predicted),
                                             ncol = 2, 
                                             byrow = F))$weighted.kappa
    
  }
  
  #Get best Kappa and Lambda for the fold
  best_lambda[fold] <- res.ordreg$lambdas[test_kappas == max(test_kappas)]
  best_kappa[fold] <- test_kappas[test_kappas == max(test_kappas)]
  res.ordreg$testing_kappa <- test_kappas
  all_model_info[[fold]] <- res.ordreg
  
}

data.frame(fold = 1:5,
           best_lambda,
           best_kappa)

```

```{r}

#pdf(file = "C:/Users/brian/Documents/Grad School/BIOS 735/HOOVS/nonzero_v_kappa.pdf")
for( i in 1:5){
  plot_data <- data.frame(n.nonzero = all_model_info[[i]]$n.nonzero, 
                          testing_kappa = all_model_info[[i]]$testing_kappa, 
                          lambdas = all_model_info[[i]]$lambdas)
  
  p <- ggplot(plot_data, aes(n.nonzero, testing_kappa)) +
    geom_point() +
    geom_label(aes(label=lambdas, fill=NULL), nudge_x = 10, alpha = 0.1, label.size = 0) +
    labs(title = paste0("Fold ", i))
  
  p1 <- ggplot(plot_data, aes(log(n.nonzero), testing_kappa)) +
    geom_point() +
    geom_label(aes(label=lambdas, fill=NULL), nudge_x = 0.1, alpha = 0.1, label.size = 0) +
    labs(title = paste0("Fold ", i, ": log(n.nonzero)"))
  
  print(p)
  print(p1)
}
#dev.off()


```